name: DeterCode Linux Engine Build and Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Depodaki Kodları Çek
      uses: actions/checkout@v4

    - name: C++ Derleyicisini Kontrol Et (g++)
      run: g++ --version

    - name: DeterCode Çekirdeğini Linux İçin Derle
      run: g++ -O3 app/src/main/cpp/motor_cekirdegi.cpp -o detercode_engine

    - name: Motor Marşına Bas ve Test Et (Run DeterCode)
      run: ./detercode_engine
      
