name: DeterCode Native Bulut Derleyici

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları Depodan Çek
      uses: actions/checkout@v4

    - name: C++ Çekirdeğini Derle (V8.0 Native Engine)
      run: |
        g++ -O3 -std=c++17 -o dtermotor motor_cekirdegi.cpp
        echo "C++ Çekirdeği saf makine koduna başarıyla dönüştürüldü."

    - name: DeterCode Derleyicisini Çalıştır
      run: |
        python3 compiler.py seneryolar/evrimsel_savas.deter

    - name: Native Çıktıları Paketle ve Hazırla
      uses: actions/upload-artifact@v4
      with:
        name: DeterCode-Native-Paket
        path: |
          dist/
          dtermotor
          
