name: DeterCode Android APK Derleme

on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları Depodan Çek
      uses: actions/checkout@v4

    - name: Java Kurulumu Yap (Gradle İçin)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Gradle'ı Çalıştırılabilir Yap
      run: chmod +x gradlew
      continue-on-error: true # Eğer gradlew dosyası yoksa hata fırlatıp durmasın

    - name: Android APK'sını Derle (Bulut Garajı)
      run: ./gradlew assembleDebug
      
